[GLOBAL]
pants_version = "2.11.0"
pythonpath = ["%(buildroot)s/tools/pants-plugins"]
backend_packages = [
    "pants.backend.python",
    "pants.backend.python.lint.flake8",
    "pants.backend.python.typecheck.mypy",
    "pants.backend.experimental.python",
    "setupgen",
]
pants_ignore = [
    "scripts",
    "plugins",
    "docs",  # TODO: docs build config
]

[anonymous-telemetry]
enabled = false

[source]
root_patterns = ["src", "tests", "tools/pants-plugins"]

[python]
enable_resolves = true
resolves = { python-default = "python.lock" }
interpreter_constraints = ["CPython>=3.10"]

# [setup-py-generation]
# first_party_depenency_version_scheme = "exact"

[flake8]
version = "flake8>=4.0"
extra_requirements.add = [
    "flake8-commas>=2.1",
    "setuptools>=60.0",
]
lockfile = "tools/flake8.lock"

[pytest]
version = "pytest>=7.0"
extra_requirements.add = [
    "pytest-asyncio>=0.18",
    "pytest-aiohttp>=1.0.4",
    "pytest-mock>=3.5.0",
]
args = ["-v", "-m", "'not integration'"]
lockfile = "tools/pytest.lock"

[mypy]
version = "mypy>=0.950"
extra_requirements.add = [
]
lockfile = "tools/mypy.lock"
