name: timeline-check

on: [pull_request]

jobs:
  towncrier:
    runs-on: ubuntu-latest
    steps:
    - name: Sparse-checkout
      uses: lablup/sparse-checkout@v1
      with:
        patterns: |
          changes
          scripts
          packages
          requirements
          src/ai/backend/meta
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        cache: "pip"
        cache-dependency-path: |
          setup.cfg
          requirements/build.txt
    - name: Specialize to package
      run: |
        python scripts/specialize.py meta
    - name: Install dependencies
      run: |
        python -m pip install -U pip setuptools
        python -m pip install -U -r requirements/build.txt
    - name: Check existence of news fragment
      run: |
        git fetch --no-tags origin +refs/heads/${BASE_BRANCH}:refs/remotes/origin/${BASE_BRANCH}
        python -m towncrier.check --compare-with=origin/${BASE_BRANCH}
      env:
        BASE_BRANCH: ${{ github.base_ref }}
